app = "telegram-bot-usmf8w"
primary_region = "iad"

[build]
  image = "python:3.11"

[processes]
  app = "python bot.py"

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    port = 22
